name: Daily Prediction

on:
  schedule:
    - cron: '30 0 * * *'  # Runs every day at 6:00 AM IST (UTC+5:30)
  workflow_dispatch:  # Optional manual run button in GitHub UI

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run prediction script
      run: python run_prediction.py

    - name: Commit updated predictions
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add predictions_output.csv
        git commit -m "🔁 Auto-update predictions (GitHub Actions)" || echo "No changes to commit"
        git push
